# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0159e81a03f4effbe730163da19221aee127bdcf6859b4f2ee17ffb6d74ce715e4663a2d64fbc6fa892e369b7587b6b38ec012bba3235245750a4c8ba3ff1d5c

test:
  secret_key_base: d8829679a2d50bc33896087189028b4f385482f95db8fd01629ee1228710accf6d694ff247034faafd1ae43e05eb61e22a7468d6d1baad1c6c6331d4d06c0ca1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
